name: Push

on:
  check_suite:
    types: [completed]

jobs:
  push:
    runs-on: ubuntu-latest
    name: normal-workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
