name: Push

on:
  push:
    branches:
      - master


jobs:
  check1:
    runs-on: ubuntu-latest
    name: normal-workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
  check2:
    runs-on: ubuntu-latest
    name: normal-workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
